postgresql: &postgresql
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: password

development:
  <<: *postgresql
  database: example_development

test:
  <<: *postgresql
  database: example_test

production:
  <<: *postgresql
  database: example_production
